name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    env:
      working-directory: ./docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@6e1964dde3397a825e79e4607ad57f3f7ca2c7cb
        with:
          version: 6.27.1
        working-directory: ${{env.working-directory}}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
        working-directory: ${{env.working-directory}}
      - run: pnpm i
        working-directory: ${{env.working-directory}}
      - name: Build
        run: pnpm docs:build
        working-directory: ${{env.working-directory}}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.working-directory}}/.vitepress/dist